Feature products
DamianCichyy/IceCream-TeamProject pull request #7
Opened 2022-10-15 21:37 UTC by annafrymark

2022-10-16 10:08 UTC, dominikszajbler approved these changes

2022-10-16 10:08 UTC, dominikszajbler approved these changes

2022-10-16 13:38 UTC, DamianCichyy requested changes
Błąd przy ładowaniu strony.

C:\Users\Asus\OneDrive\Pulpit\GoIt\IceCream-grp4-TeamProject\IceCream-TeamProject\src\sass\images\products\home-pic3-mobile@2x.png: ENOENT: no such file or directory, open 'C:\Users\Asus\OneDrive\Pulpit\GoIt\IceCream-grp4-TeamProject\IceCream-TeamProject\src\sass\images\products\home-pic3-mobile@2x.png'

2022-10-16 17:05 UTC, annafrymark commented
wprowadziłam zmiany, są poprawione ścieżki do plików, zobacz proszę czy teraz już jest ok?

2022-10-17 07:05 UTC, DamianCichyy requested changes
Wyskakuje błąd przy ładowaniu strony:

C:\Users\Asus\OneDrive\Pulpit\GoIt\IceCream-grp4-TeamProject\IceCream-TeamProject\src\sass\images\products\home-pic2-mobile.png: ENOENT: no such file or directory, open 'C:\Users\Asus\OneDrive\Pulpit\GoIt\IceCream-grp4-TeamProject\IceCream-TeamProject\src\sass\images\products\home-pic2-mobile.png'

Zauważ że masz taką ścieżkę  \src\sass\images\ a folder images nie znajduje się w folderze sass i chyba przez to jest błąd.

2022-10-17 15:39 UTC, dominikszajbler approved these changes

2022-10-17 20:11 UTC, DamianCichyy approved these changes
Wszystko działa brawo !

2022-10-17 20:12 UTC, merged